export type WcagLevel = 'A' | 'AA' | 'AAA';

export interface WcagCriterion {
  /** Bare number, e.g. "1.4.3". */
  num: string;
  name: string;
  level: WcagLevel;
  principle: 'Perceivable' | 'Operable' | 'Understandable' | 'Robust';
  /** Plain-language summary aimed at a frontend developer. */
  summary: string;
  /** Concrete things this tends to mean in components. */
  devNotes: string[];
  understandingUrl: string;
}

const U = (slug: string) =>
  `https://www.w3.org/WAI/WCAG22/Understanding/${slug}.html`;

/**
 * Curated WCAG 2.2 Level A and AA success criteria, phrased for developers.
 * This is a working reference, not the normative text — always link out to the
 * "Understanding" document for the full definition.
 */
export const WCAG_CRITERIA: WcagCriterion[] = [
  {
    num: '1.1.1',
    name: 'Non-text Content',
    level: 'A',
    principle: 'Perceivable',
    summary: 'Every image, icon, or non-text control has a text alternative that serves the same purpose.',
    devNotes: [
      'Informative <img> needs meaningful alt; decorative <img> needs alt="" (not a missing attribute).',
      'Icon-only buttons need an accessible name via aria-label or visually-hidden text.',
      'Inline SVGs used as images need role="img" + <title>, or aria-label.',
    ],
    understandingUrl: U('non-text-content'),
  },
  {
    num: '1.2.2',
    name: 'Captions (Prerecorded)',
    level: 'A',
    principle: 'Perceivable',
    summary: 'Prerecorded video with audio has synchronized captions.',
    devNotes: ['Provide a <track kind="captions"> on <video>.'],
    understandingUrl: U('captions-prerecorded'),
  },
  {
    num: '1.3.1',
    name: 'Info and Relationships',
    level: 'A',
    principle: 'Perceivable',
    summary: 'Structure conveyed visually (headings, lists, tables, labels, groups) is also available in markup.',
    devNotes: [
      'Use real <h1>–<h6>, <ul>/<ol>, <table> with <th>, <fieldset>/<legend>.',
      'Associate every form control with a <label> (for/id) or aria-labelledby.',
      'Don’t fake a heading with a bold <div>.',
    ],
    understandingUrl: U('info-and-relationships'),
  },
  {
    num: '1.3.2',
    name: 'Meaningful Sequence',
    level: 'A',
    principle: 'Perceivable',
    summary: 'The DOM order produces a reading order that makes sense.',
    devNotes: ['Order content in the DOM logically; use CSS for visual placement, not order hacks that break meaning.'],
    understandingUrl: U('meaningful-sequence'),
  },
  {
    num: '1.3.3',
    name: 'Sensory Characteristics',
    level: 'A',
    principle: 'Perceivable',
    summary: 'Instructions don’t rely only on shape, size, or position ("click the round button on the right").',
    devNotes: ['Reference controls by their visible label or name as well as position.'],
    understandingUrl: U('sensory-characteristics'),
  },
  {
    num: '1.3.4',
    name: 'Orientation',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'Content isn’t locked to portrait or landscape unless essential.',
    devNotes: ['Avoid CSS/JS that hard-locks orientation.'],
    understandingUrl: U('orientation'),
  },
  {
    num: '1.3.5',
    name: 'Identify Input Purpose',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'Inputs collecting known user data expose their purpose programmatically.',
    devNotes: ['Set appropriate autocomplete tokens (name, email, tel, street-address, …).'],
    understandingUrl: U('identify-input-purpose'),
  },
  {
    num: '1.4.1',
    name: 'Use of Color',
    level: 'A',
    principle: 'Perceivable',
    summary: 'Color is never the only way information is conveyed.',
    devNotes: [
      'Error states need an icon or text, not just red.',
      'Links in body text need an underline or another non-color cue.',
      'Chart series need labels/patterns, not color alone.',
    ],
    understandingUrl: U('use-of-color'),
  },
  {
    num: '1.4.2',
    name: 'Audio Control',
    level: 'A',
    principle: 'Perceivable',
    summary: 'Audio that plays for more than 3s can be paused, stopped, or muted independently.',
    devNotes: ['Don’t autoplay unmuted media; provide controls.'],
    understandingUrl: U('audio-control'),
  },
  {
    num: '1.4.3',
    name: 'Contrast (Minimum)',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'Text has ≥ 4.5:1 contrast (≥ 3:1 for large text ≥ 24px, or ≥ 18.66px bold).',
    devNotes: [
      'Check placeholder, disabled-looking, and hover/focus text too.',
      'Gradients and images behind text are a common failure.',
    ],
    understandingUrl: U('contrast-minimum'),
  },
  {
    num: '1.4.4',
    name: 'Resize Text',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'Text can be resized to 200% without loss of content or function.',
    devNotes: ['Use rem/em; avoid fixed px heights on text containers; don’t disable zoom.'],
    understandingUrl: U('resize-text'),
  },
  {
    num: '1.4.5',
    name: 'Images of Text',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'Use real text instead of pictures of text (except logos).',
    devNotes: ['Render headings and UI copy as text with CSS, not baked into images.'],
    understandingUrl: U('images-of-text'),
  },
  {
    num: '1.4.10',
    name: 'Reflow',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'Content reflows to a 320px-wide viewport with no two-dimensional scrolling.',
    devNotes: ['No fixed-width layouts; let content wrap; horizontal scroll only for data tables, code, maps.'],
    understandingUrl: U('reflow'),
  },
  {
    num: '1.4.11',
    name: 'Non-text Contrast',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'UI component boundaries and states, and meaningful graphics, have ≥ 3:1 contrast.',
    devNotes: ['Input borders, focus rings, toggle states, icon buttons must be visible against their background.'],
    understandingUrl: U('non-text-contrast'),
  },
  {
    num: '1.4.12',
    name: 'Text Spacing',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'No loss of content when users override line-height, paragraph, letter, and word spacing.',
    devNotes: ['Avoid fixed heights with overflow:hidden on text; test with the text-spacing bookmarklet.'],
    understandingUrl: U('text-spacing'),
  },
  {
    num: '1.4.13',
    name: 'Content on Hover or Focus',
    level: 'AA',
    principle: 'Perceivable',
    summary: 'Hover/focus-triggered content is dismissible, hoverable, and persistent.',
    devNotes: [
      'Tooltips must not vanish when the pointer moves toward them.',
      'Esc should dismiss without moving focus; content stays until dismissed or no longer valid.',
    ],
    understandingUrl: U('content-on-hover-or-focus'),
  },
  {
    num: '2.1.1',
    name: 'Keyboard',
    level: 'A',
    principle: 'Operable',
    summary: 'All functionality is available from a keyboard.',
    devNotes: [
      'Use <button>/<a>, not <div onclick>.',
      'Custom widgets need key handlers (Enter/Space/arrows) and be focusable.',
      'No mouse-only interactions.',
    ],
    understandingUrl: U('keyboard'),
  },
  {
    num: '2.1.2',
    name: 'No Keyboard Trap',
    level: 'A',
    principle: 'Operable',
    summary: 'Keyboard focus can always move away from a component.',
    devNotes: ['Modals: trap focus but allow Esc/close; never trap in a widget with no exit.'],
    understandingUrl: U('no-keyboard-trap'),
  },
  {
    num: '2.1.4',
    name: 'Character Key Shortcuts',
    level: 'A',
    principle: 'Operable',
    summary: 'Single-character shortcuts can be turned off, remapped, or are active only on focus.',
    devNotes: ['Guard global "j/k" style shortcuts; ignore them while a text field has focus.'],
    understandingUrl: U('character-key-shortcuts'),
  },
  {
    num: '2.4.1',
    name: 'Bypass Blocks',
    level: 'A',
    principle: 'Operable',
    summary: 'A way to skip repeated blocks (a skip link and/or landmarks).',
    devNotes: ['Provide a visible-on-focus "Skip to main content" link; use <header>/<nav>/<main>/<footer>.'],
    understandingUrl: U('bypass-blocks'),
  },
  {
    num: '2.4.2',
    name: 'Page Titled',
    level: 'A',
    principle: 'Operable',
    summary: 'Each page has a descriptive, unique <title>.',
    devNotes: ['In SPAs, update document.title on route change.'],
    understandingUrl: U('page-titled'),
  },
  {
    num: '2.4.3',
    name: 'Focus Order',
    level: 'A',
    principle: 'Operable',
    summary: 'Focus moves in an order that preserves meaning and operability.',
    devNotes: ['Avoid positive tabindex; manage focus when inserting/removing content and opening dialogs.'],
    understandingUrl: U('focus-order'),
  },
  {
    num: '2.4.4',
    name: 'Link Purpose (In Context)',
    level: 'A',
    principle: 'Operable',
    summary: 'The purpose of each link is clear from its text (with its context).',
    devNotes: ['Avoid "click here"/"read more" as the whole link; or add aria-label with the full purpose.'],
    understandingUrl: U('link-purpose-in-context'),
  },
  {
    num: '2.4.5',
    name: 'Multiple Ways',
    level: 'AA',
    principle: 'Operable',
    summary: 'More than one way to find a page (nav + search, sitemap, etc.).',
    devNotes: ['Provide site search or a sitemap in addition to primary navigation.'],
    understandingUrl: U('multiple-ways'),
  },
  {
    num: '2.4.6',
    name: 'Headings and Labels',
    level: 'AA',
    principle: 'Operable',
    summary: 'Headings and labels describe their topic or purpose.',
    devNotes: ['Make labels specific ("Work email", not "Email 2"); headings should summarize their section.'],
    understandingUrl: U('headings-and-labels'),
  },
  {
    num: '2.4.7',
    name: 'Focus Visible',
    level: 'AA',
    principle: 'Operable',
    summary: 'The keyboard focus indicator is visible.',
    devNotes: ['Never `outline:none` without a replacement; style :focus-visible with a clear ring.'],
    understandingUrl: U('focus-visible'),
  },
  {
    num: '2.4.11',
    name: 'Focus Not Obscured (Minimum)',
    level: 'AA',
    principle: 'Operable',
    summary: 'A focused element is not entirely hidden by sticky headers/footers or other content.',
    devNotes: ['Add scroll-padding for sticky headers; check focus visibility with dialogs and cookie bars.'],
    understandingUrl: U('focus-not-obscured-minimum'),
  },
  {
    num: '2.5.1',
    name: 'Pointer Gestures',
    level: 'A',
    principle: 'Operable',
    summary: 'Multipoint or path-based gestures have a single-pointer alternative.',
    devNotes: ['Swipe/pinch/drag features need button or tap equivalents.'],
    understandingUrl: U('pointer-gestures'),
  },
  {
    num: '2.5.2',
    name: 'Pointer Cancellation',
    level: 'A',
    principle: 'Operable',
    summary: 'Actions trigger on up-event, or can be aborted/undone.',
    devNotes: ['Don’t fire critical actions on mousedown/touchstart.'],
    understandingUrl: U('pointer-cancellation'),
  },
  {
    num: '2.5.3',
    name: 'Label in Name',
    level: 'A',
    principle: 'Operable',
    summary: 'A control’s accessible name contains its visible label text.',
    devNotes: ['If the visible text is "Search", don’t set aria-label="Submit"; voice-control users say what they see.'],
    understandingUrl: U('label-in-name'),
  },
  {
    num: '2.5.4',
    name: 'Motion Actuation',
    level: 'A',
    principle: 'Operable',
    summary: 'Features triggered by device motion have a UI alternative and can be disabled.',
    devNotes: ['Shake-to-undo needs a button too.'],
    understandingUrl: U('motion-actuation'),
  },
  {
    num: '2.5.7',
    name: 'Dragging Movements',
    level: 'AA',
    principle: 'Operable',
    summary: 'Anything done by dragging can also be done with a single pointer without dragging.',
    devNotes: ['Sliders, reorderable lists, kanban boards need click/tap or button alternatives.'],
    understandingUrl: U('dragging-movements'),
  },
  {
    num: '2.5.8',
    name: 'Target Size (Minimum)',
    level: 'AA',
    principle: 'Operable',
    summary: 'Pointer targets are at least 24×24 CSS px, or have enough spacing.',
    devNotes: ['Icon buttons, close buttons, and inline link clusters are the usual offenders.'],
    understandingUrl: U('target-size-minimum'),
  },
  {
    num: '3.1.1',
    name: 'Language of Page',
    level: 'A',
    principle: 'Understandable',
    summary: 'The default human language is set on <html>.',
    devNotes: ['<html lang="en"> (a valid BCP-47 tag).'],
    understandingUrl: U('language-of-page'),
  },
  {
    num: '3.1.2',
    name: 'Language of Parts',
    level: 'AA',
    principle: 'Understandable',
    summary: 'Passages in another language carry their own lang attribute.',
    devNotes: ['<span lang="fr">…</span> for inline foreign phrases.'],
    understandingUrl: U('language-of-parts'),
  },
  {
    num: '3.2.1',
    name: 'On Focus',
    level: 'A',
    principle: 'Understandable',
    summary: 'Moving focus to a component doesn’t trigger a change of context.',
    devNotes: ['No auto-submit or navigation purely on focus.'],
    understandingUrl: U('on-focus'),
  },
  {
    num: '3.2.2',
    name: 'On Input',
    level: 'A',
    principle: 'Understandable',
    summary: 'Changing a setting doesn’t automatically change context unless the user was warned.',
    devNotes: ['Don’t navigate on <select> change without a Go button or prior warning.'],
    understandingUrl: U('on-input'),
  },
  {
    num: '3.2.3',
    name: 'Consistent Navigation',
    level: 'AA',
    principle: 'Understandable',
    summary: 'Repeated navigation appears in the same relative order across pages.',
    devNotes: ['Keep the header/nav structure stable between routes.'],
    understandingUrl: U('consistent-navigation'),
  },
  {
    num: '3.2.4',
    name: 'Consistent Identification',
    level: 'AA',
    principle: 'Understandable',
    summary: 'Components with the same function are labeled consistently.',
    devNotes: ['Pick one name for "Delete" and use it everywhere; same icons for same actions.'],
    understandingUrl: U('consistent-identification'),
  },
  {
    num: '3.2.6',
    name: 'Consistent Help',
    level: 'A',
    principle: 'Understandable',
    summary: 'Help mechanisms (contact, chat, FAQ link) appear in a consistent location.',
    devNotes: ['Keep the "Help"/"Contact" affordance in the same place across pages.'],
    understandingUrl: U('consistent-help'),
  },
  {
    num: '3.3.1',
    name: 'Error Identification',
    level: 'A',
    principle: 'Understandable',
    summary: 'Input errors are identified in text and the item in error is named.',
    devNotes: ['Describe the error in words; link/associate it with the field via aria-describedby.'],
    understandingUrl: U('error-identification'),
  },
  {
    num: '3.3.2',
    name: 'Labels or Instructions',
    level: 'A',
    principle: 'Understandable',
    summary: 'Form controls have labels or instructions where needed.',
    devNotes: ['Every control has a persistent visible label; placeholder is not a label.'],
    understandingUrl: U('labels-or-instructions'),
  },
  {
    num: '3.3.3',
    name: 'Error Suggestion',
    level: 'AA',
    principle: 'Understandable',
    summary: 'When you know how to fix an error, tell the user.',
    devNotes: ['"Date must be in the future", not just "Invalid".'],
    understandingUrl: U('error-suggestion'),
  },
  {
    num: '3.3.4',
    name: 'Error Prevention (Legal, Financial, Data)',
    level: 'AA',
    principle: 'Understandable',
    summary: 'Consequential submissions are reversible, checked, or confirmed.',
    devNotes: ['Add a review/confirm step or undo for payments, deletions, legal agreements.'],
    understandingUrl: U('error-prevention-legal-financial-data'),
  },
  {
    num: '3.3.7',
    name: 'Redundant Entry',
    level: 'A',
    principle: 'Understandable',
    summary: 'Information already entered is auto-populated or selectable, not re-typed.',
    devNotes: ['"Billing address same as shipping" checkbox; carry data across multi-step forms.'],
    understandingUrl: U('redundant-entry'),
  },
  {
    num: '3.3.8',
    name: 'Accessible Authentication (Minimum)',
    level: 'AA',
    principle: 'Understandable',
    summary: 'No cognitive function test (puzzle, transcription) required to log in.',
    devNotes: ['Allow password managers/paste; offer email link or passkey; don’t block autofill.'],
    understandingUrl: U('accessible-authentication-minimum'),
  },
  {
    num: '4.1.2',
    name: 'Name, Role, Value',
    level: 'A',
    principle: 'Robust',
    summary: 'For every UI component, the name, role, and state are exposed to assistive tech.',
    devNotes: [
      'Prefer native elements; if you build a widget, follow the ARIA Authoring Practices pattern.',
      'Keep aria-expanded / aria-checked / aria-selected in sync with the visual state.',
    ],
    understandingUrl: U('name-role-value'),
  },
  {
    num: '4.1.3',
    name: 'Status Messages',
    level: 'AA',
    principle: 'Robust',
    summary: 'Status updates are announced without moving focus.',
    devNotes: ['Use role="status" / aria-live="polite" for "Saved", result counts, toast notifications.'],
    understandingUrl: U('status-messages'),
  },
];

export const PRINCIPLES = ['Perceivable', 'Operable', 'Understandable', 'Robust'] as const;
